//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Election
    {
        public int Id { get; set; }
        public string CampaignName { get; set; }
        public string ParticipantName1 { get; set; }
        public string ParticipantName2 { get; set; }
        public string Content1 { get; set; }
    }
}
